sonar.projectKey=wanderlust
sonar.organization=wanderlust
sonar.projectName=Wanderlust
sonar.sources=backend,frontend
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/package-lock.json
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info
